services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: radegondes123
      MONGO_INITDB_DATABASE: radegondes
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: